### PR TITLE
Reorganize some components

### PR DESCRIPTION
**Pull request by mythmon**
While introducing @Riddlerat to the codebase, I noticed some ways that the code could be streamlined a bit.

### CODE REVIEW

**Comment by mythmon** [comment]
bors delegate= @Riddlerat

**Comment by Riddlerat** [comment]
@mythmon when I run your branch I'm seeing a console error, looking at the commit history of your branch it looks like  #11 might not be added in this branch, I figured I would call it out but I'm not sure that it's a problem?

```mapStateToProps() in Connect(MetaControls) must return a plain object. Instead received undefined.```

**Comment by Riddlerat** [comment]
Hmm now that I'm poking at it more it I don't think the branch not containing #11 is related at all, sorry for the Red herring.

I think the console error is still an issue though, I'm not sure how much of one.

**Comment by mythmon** [comment]
I wrote a test that rendered the component throwing the error. That didn't fail the tests though, because `redux` wasn't actually throwing an error, just printing one. So I went further and configured Jest to throw an error if any test ever calls `console.warn` or `console.error`. That might be a bit overboard and come back to bite us later, but it made the test correctly fail.

The root of the issue was that I made the default value for connect's parameters return undefined, which Redux's `connect` isn't ok with. I fixed the types to not allow that, and changed the default.

**Comment by Riddlerat** [comment]
Looks good to me!
bors r+

**Pull request merged**
